apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: esearch
  name: esearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: esearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: esearch
    spec:
      containers:
        - env:
            - name: discovery.type
              value: single-node
          image: elasticsearch:7.5.0
          name: esearch
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: esearch-data
      restartPolicy: Always
      volumes:
        - name: esearch-data
          persistentVolumeClaim:
            claimName: esearch-data
status: {}
