# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose convert
#     kompose.version: 1.22.0 (955b78124)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: redis
#   name: redis
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: redis
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose convert
#         kompose.version: 1.22.0 (955b78124)
#       creationTimestamp: null
#       labels:
#         io.kompose.service: redis
#     spec:
#       containers:
#         - image: library/redis:5.0-alpine
#           name: redis
#           resources: {}
#           volumeMounts:
#             - mountPath: /data
#               name: redis-data
#       restartPolicy: Always
#       volumes:
#         - name: redis-data
#           persistentVolumeClaim:
#             claimName: redis-data
# status: {}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: web
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
        tier: backend
    spec:
      containers:
        - image: ibrary/redis:5.0-alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data