
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${EC2_SERVER_IP}" >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_SERVER_IP: ${{ secrets.EC2_SERVER_IP }}

    - name: Stop and Remove Containers
      run: |
        # SSH into your EC2 server and stop/remove containers using docker-compose (if applicable)
        ssh ubuntu@ip-172-31-92-48 'cd /home/ubuntu/my-test-Saelor-app-repo && docker-compose down -v'

    - name: Remove Old Docker Images
      run: |
        # SSH into your EC2 server and remove old Docker images
        ssh ubuntu@ip-172-31-92-48 'docker images -q | xargs -r docker rmi -f'

    - name: Build and Tag Docker Image
      run: |
        # SSH into your EC2 server and build the new Docker image
        ssh ubuntu@ip-172-31-92-48 'cd /home/ubuntu/my-test-Saelor-app-repo && docker build -t my-app-image .'

