
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${EC2_SERVER_IP}" >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_SERVER_IP: ${{ secrets.EC2_SERVER_IP }}

    - name: Deploy to EC2
      run: |
        ssh ubuntu@44.217.238.13 'cd /home/ubuntu/my-test-Saelor-app-repo && git pull origin main && docker build -t my-app-image .'


